version: '3'

services:

  api-service:
    build:
      context: ./
      dockerfile: ./carddeck.dockerfile
    restart: "no"
    ports:
      - "6555:8080"
    deploy:
      mode: replicated
      replicas: 1
    environment:
      dsn: "host=postgres port=5432 user=postgres password=postgres dbname=cardsDB sslmode=disable timezone=UTC connect_timeout=5"

  postgres:
    image: 'postgres:14.5'
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cardsDB
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - '5432:5432'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql